FROM python:3.12-slim

WORKDIR /app

# Copier les fichiers du projet
COPY . /app

# Installer les dépendances
RUN pip install --no-cache-dir flask mysql-connector-python

# Exposer le port Flask
EXPOSE 5000

# Lancer l'app
CMD ["python", "app.py"]
