services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=arthur_scrapy
      - MYSQL_DATABASE=comparator
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
